#!/bin/sh
curl -v \
    -H 'Content-Type: text/xml; charset=utf-8' \
    -H 'SOAPAction: "urn:schemas-upnp-org:service:AVTransport:1#SetAVTransportURI"' \
    --data-binary @xml/gupnp-set-uri \
    'http://10.0.0.5/UD/?2'

curl -v \
    -H 'Content-Type: text/xml; charset=utf-8' \
    -H 'SOAPAction: "urn:schemas-upnp-org:service:AVTransport:1#Play"' \
    --data-binary @xml/gupnp-play \
    'http://10.0.0.5/UD/?2'
