#!/bin/bash
pattern=$1
pacmd list-sink-inputs | \
    perl -nle '
        $lastindex = $1 if /^\s*index: (\d+)/;
        print($lastindex), exit if /^\s*client: \d+ <.*?(?i:'"$pattern"').*?>/
                                or /^\s*application\.process\.binary\s*=\s*".*?(?i:'"$pattern"'.*?)/;
    '
