#!/usr/bin/env perl
use strict;
use warnings;
use feature qw(say);

use List::MoreUtils qw(firstidx);
use Soundbridge::Remote;

my $sb = Soundbridge::Remote->new;


if (my $play = join ' ', @ARGV) {
    my $index = $play-1;  
    my $name = $sb->preset_name($index);
    say "Playing ${name}... ";
    $sb->play_preset($index);
} else {
    my $i = 1;
    printf "%2d. %s\n", $i++, $_
        for $sb->rcp('ListPresets');
}
