#!/usr/bin/env perl
use strict;
use warnings;

use Soundbridge;

my $sb  = Soundbridge->new();
my $url = shift @ARGV
    or die "usage: $0 url\n";

# XXX TODO: This format "detection" is crap. Use HEAD to get Content-Type
# and normalize to what RCP accepts.
my ($ext) = ($url =~ /\.(\w+)$/);

$sb->send(<<".");
ServerDisconnect
SetServerFilter radio
ListServers
ServerConnect 0
ClearWorkingSong
SetWorkingSongInfo title $url
SetWorkingSongInfo url $url
SetWorkingSongInfo format \U$ext\E
QueueAndPlayOne working
.
