#!/usr/bin/env perl
use strict;
use warnings;
use feature qw(say);

use List::MoreUtils qw(firstidx);
use Soundbridge;

my $sb = Soundbridge->new;
my @presets = $sb->rcp('ListPresets');

if (my $play = join ' ', @ARGV) {
    my $index = $play =~ /\D/
                    ? firstidx { /$play/i } @presets
                    : $play - 1;
    say "Playing $presets[$index]... ";
    $sb->rcp("PlayPreset $index");
} else {
    say $_+1, ". $presets[$_]" for 0..$#presets;
}
