#!/usr/bin/env perl
use strict;
use warnings;
use open qw/ :utf8 :std /;
use utf8;
use feature qw/ say /;

use Soundbridge;

my $sb     = Soundbridge->new;
my $volume = shift @ARGV;

# Suppress warnings about errors when the device is off
$sb->log_level(0);

my @song = $sb->get("CurrentSongInfo");
my ($title)  = grep { s/^title: +//  } @song;
my ($artist) = grep { s/^artist: +// } @song;

if ($title or $artist) {
    say "🎶  " . join "\n   ", grep { $_ } $artist, $title;
} else {
    say "🔇  Not playing.";
}
