#!/usr/bin/env perl
use strict;
use warnings;
use open qw/ :utf8 :std /;
use utf8;
use feature qw/ say /;

use Soundbridge;

my $sb     = Soundbridge->new;
my $volume = shift @ARGV;

# Suppress warnings about errors when the device is off
$sb->log_level(0);

my ($title) = grep { s/^title: +// } $sb->get("CurrentSongInfo");

if (defined $title and length $title) {
    say "🎶  $title";
} else {
    say "🔇  Not playing.";
}
