#!/bin/bash
dst=$1
shift
src=${1:-spotify}

# This is ugly, but I don't want to refactor it right now
if [[ $dst != "preset" ]]; then
    inputidx=$(find-sink-input "$src")

    if [[ -z $inputidx ]]; then
        echo Unable to find sink input index for $src
        exit 1
    fi
fi

function move_to_sink() {
    # takes only a sink
    echo "Streaming $src ($inputidx) to $dst ($1)"
    pactl move-sink-input $inputidx $1
}

case "$dst" in
    home|soundbridge|sb)
        sink='streaming'
        pacmd set-sink-mute $sink 0 >/dev/null
        pacmd set-source-mute $sink.monitor 0 >/dev/null
        soundbridge-upnp-play $sink
        move_to_sink $sink
        ;;
    bps|work|office)
        sink='raop.Conference-Room.local'
        gconftool -s --type bool /system/pulseaudio/modules/raop-discover/enabled true
        sleep 5
        pacmd set-sink-mute $sink 0 >/dev/null
        move_to_sink $sink
        ;;
    preset)
        play-preset "$@"
        exit
        ;;
    alsa|local|hw|off|stop)
        move_to_sink 0
        gconftool -s --type bool /system/pulseaudio/modules/raop-discover/enabled false
        ;;
    *)
        echo "Uh, what?"
        exit 1
        ;;
esac

