#!/bin/bash
dst=$1
shift
src=${1:-Banshee}

# This is ugly, but I don't want to refactor it right now
if [[ $dst != "preset" ]]; then
    inputidx=$(find-sink-input "$src")

    if [[ -z $inputidx ]]; then
        echo Unable to find sink input index for $src
        exit 1
    fi
fi

case "$dst" in
    home|soundbridge|sb)
        sink='streaming'
        pacmd set-sink-mute $sink 0 >/dev/null
        pacmd set-source-mute $sink.monitor 0 >/dev/null
        soundbridge-upnp-play $sink
        ;;
    bps|work|office)
        sink='raop.Conference-Room.local'
        gconftool -s --type bool /system/pulseaudio/modules/raop-discover/enabled true
        sleep 5
        pacmd set-sink-mute $sink 0 >/dev/null
        ;;
    preset)
        play-preset "$@"
        exit
        ;;
    alsa|local|hw|off)
        sink=0
        ;;
    *)
        echo "Uh, what?"
        exit 1
        ;;
esac

echo "Streaming $src ($inputidx) to $dst ($sink)"
pactl move-sink-input $inputidx $sink

# After moving the sink away, turn off some pulse features
if [[ $sink == 0 ]]; then
    gconftool -s --type bool /system/pulseaudio/modules/raop-discover/enabled false
fi
